name: Famara
version: '1.0-SNAPSHOT'
main: com.wenkrang.famara.Famara
# 自 1.20.5 以来，Spigot 支持在 api-version 中使用小版本
api-version: '1.21.2'
commands:
  fa:
      description: Famara
      usage: /fa
      aliases: [famara]

libraries:
  - "com.maxmind.geoip2:geoip2:4.3.1"